### ISSUE TITLE
Enhancement: Include Local Setup Instructions in README

### ISSUE THREAD

**Issue by pratyushsingha** [Abbhiishek/codecommunitymusic-client#23]
### Issue

The current README for this project lacks instructions on how to set up the project locally. Providing clear and comprehensive local setup instructions is essential for new contributors and users who want to try out the project. 

### Suggested Solution

I suggest that we enhance the README by adding a section that outlines the steps to set up the project on a local development environment. This will include prerequisites, installation steps, basic usage instructions and how to connect with the backends 

### Benefits

- Helps new contributors and users get started quickly.
- Reduces confusion and support requests related to project setup.
- Encourages more people to try out and contribute to the project.

### Proposed Changes

In the updated README, we should include the following sections:

- Prerequisites: List any required software or tools.
- Installation: Step-by-step instructions for setting up the project locally.
- Usage: Explain how users can interact with the project after setup.

I'm willing to contribute to this and can provide a draft of the updated README if that would be helpful.

Please let me know if you agree with this enhancement, and if so, I can start working on the changes.

**Comment by Abbhiishek** [comment]
The app uses and another peoject as its backend service.

We have to inlcude that too

**Comment by Abbhiishek** [comment]
Assigned to @pratyushsingha

**Comment by Abbhiishek** [comment]
Issue resolved ✅
