### ISSUE TITLE
Enhance Password Strength Validation 

### ISSUE THREAD

**Issue by pratyushsingha** [Abbhiishek/codecommunitymusic-client#29]
To enhance security and provide users with clearer feedback during password creation, i propose implementing an improved password strength validation

**Comment by Abbhiishek** [comment]
What your approach on this issue?

**Comment by pratyushsingha** [comment]
@Abbhiishek like the password should contains uppercase,lowercase ,numbers ,special charracters nd it will give users alert if  any of these requirements are missing

**Comment by Abbhiishek** [comment]
It seems to be a nice feature actually. It also belongs to the project roadmap soo kudos to you for rasing the issue. However i was thinking if we can implement this with a visual experience that shown to user that resembles the password strength.
Like a long strip which turns red yellow green as user password is more secured and with a proper length.

**Comment by Abbhiishek** [comment]
I have used Zod to validate the schema, you can add new parameters and also validate. The visual part is something we have to work on.

**Comment by pratyushsingha** [comment]
okkk...i am trying to do it🚀

**Comment by Abbhiishek** [comment]
Btw,

i have merged both the repos into one you can check out that if you want : https://github.com/Abbhiishek/codecommunitymusic

**Comment by pratyushsingha** [comment]
@Abbhiishek yss i saw it in the morning😁🚀

**Comment by pratyushsingha** [comment]
https://github.com/Abbhiishek/codecommunitymusic-client/assets/111200225/1dfa8a91-692a-4de6-be30-94fabd8453f3
how is it??

**Comment by pratyushsingha** [comment]
how is it??

**Comment by Abbhiishek** [comment]
Great 😃.

Give me some time to review the code .

**Comment by Abbhiishek** [comment]
> @Abbhiishek yess i saw it in the morning😁🚀

great let me know if you were able to setup the whole application. You would require docker installed in your host machine.

**Comment by pratyushsingha** [comment]
> > @Abbhiishek yess i saw it in the morning😁🚀
> 
> great let me know if you were able to setup the whole application. You would require docker installed in your host machine.

@Abbhiishek actually i have set it up one day before....from [here](https://github.com/pratyushsingha/codecommunitymusic-server)...yes yes i am able to set it up with docker

**Comment by Abbhiishek** [comment]
> > > @Abbhiishek yess i saw it in the morning😁🚀
> > 
> > 
> > great let me know if you were able to setup the whole application. You would require docker installed in your host machine.
> 
> @Abbhiishek actually i have set it up one day before....from [here](https://github.com/pratyushsingha/codecommunitymusic-server)...yes yes i am able to set it up with docker

-> Now you won't have to do soo you can follow this issue #31 . With just few commands everything would be done. You wont have to manage and create database on your own multiple times. There need some improvement regarding the image size, i would be pushing the new optimised one soon :)

**Comment by Abbhiishek** [comment]
Issue Resolved ✅
