### ISSUE TITLE
[fix] - Typo Remember in Login Page

### ISSUE THREAD

**Issue by Abbhiishek** [Abbhiishek/codecommunitymusic-client#32]
There is a typo in a login page :)

<img width="247" alt="image" src="https://github.com/Abbhiishek/codecommunitymusic-client/assets/86338762/0bc0857e-7935-47a1-a332-176b42546e87">

## Solution 

the correct spelling should be Remember :)

**Comment by snigdho442u** [comment]
hello dada

**Comment by beluga2003** [comment]
Hey @Abbhiishek can you assign me this ?

**Comment by Abbhiishek** [comment]
Sure go ahead @beluga2003
